'use client';

import React, { useState } from 'react';
import {
    FileText,
    Download,
    RefreshCw,
    CheckCircle2,
    AlertTriangle,
    TrendingUp,
    Users,
    Zap,
    Shield
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function AIReportView() {
    const [loading, setLoading] = useState(false);
    const [report, setReport] = useState<any>(null);

    const generateReport = async () => {
        setLoading(true);
        try {
            const res = await fetch('http://localhost:8080/api/ai-report', { method: 'POST' });
            const data = await res.json();
            setReport(data);
        } catch (error) {
            console.error('Failed to generate report', error);
        } finally {
            setLoading(false);
        }
    };

    const downloadPDF = () => {
        if (!report) return;
        const doc = new jsPDF();

        doc.setFontSize(20);
        doc.text('Logistics AI Operations Report', 14, 22);
        doc.setFontSize(10);
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30);

        autoTable(doc, {
            startY: 40,
            head: [['Metric', 'Value']],
            body: [
                ['Total Shipments', report.summary.totalShipments],
                ['Delivered', report.summary.delivered],
                ['Delayed', report.summary.delayed],
                ['High Risk', report.summary.highRisk],
            ],
        });

        doc.save('logistics-ai-report.pdf');
    };

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="space-y-1">
                    <h2 className="text-2xl font-bold tracking-tight">AI Operations Report</h2>
                    <p className="text-muted-foreground text-gray-400">
                        Real-time intelligence generated by Google Gemini.
                    </p>
                </div>
                <div className="flex gap-3">
                    <button
                        onClick={generateReport}
                        disabled={loading}
                        className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors disabled:opacity-50"
                    >
                        {loading ? <RefreshCw className="animate-spin" size={18} /> : <Zap size={18} />}
                        {loading ? 'Generating...' : 'Generate Report'}
                    </button>
                    {report && (
                        <button
                            onClick={downloadPDF}
                            className="flex items-center gap-2 bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded-lg font-medium transition-colors"
                        >
                            <Download size={18} /> Export PDF
                        </button>
                    )}
                </div>
            </div>

            {!report && !loading && (
                <div className="flex flex-col items-center justify-center h-[400px] border border-dashed border-white/20 rounded-xl bg-white/5">
                    <FileText size={48} className="text-gray-500 mb-4" />
                    <h3 className="text-xl font-medium text-gray-300">No Report Generated</h3>
                    <p className="text-gray-500 mt-2">Click "Generate Report" to analyze real-time data.</p>
                </div>
            )}

            {loading && (
                <div className="flex flex-col items-center justify-center h-[400px]">
                    <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-4"></div>
                    <p className="text-blue-400 animate-pulse">Analyzing logistics data with Gemini AI...</p>
                </div>
            )}

            {report && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* 1. Operations Summary */}
                    <Card className="bg-black/40 border-white/10 col-span-1 md:col-span-2">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2 text-blue-400">
                                <TrendingUp size={20} /> Operations Summary
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            <div className="p-4 bg-white/5 rounded-lg">
                                <p className="text-gray-400 text-xs">Total Shipments</p>
                                <p className="text-2xl font-bold text-white">{report.summary.totalShipments}</p>
                            </div>
                            <div className="p-4 bg-white/5 rounded-lg">
                                <p className="text-gray-400 text-xs">Delivered</p>
                                <p className="text-2xl font-bold text-green-500">{report.summary.delivered}</p>
                            </div>
                            <div className="p-4 bg-white/5 rounded-lg">
                                <p className="text-gray-400 text-xs">Delayed</p>
                                <p className="text-2xl font-bold text-red-500">{report.summary.delayed}</p>
                            </div>
                            <div className="p-4 bg-white/5 rounded-lg">
                                <p className="text-gray-400 text-xs">High Risk</p>
                                <p className="text-2xl font-bold text-orange-500">{report.summary.highRisk}</p>
                            </div>
                            <div className="col-span-2 md:col-span-4 mt-2 p-3 bg-blue-500/10 border border-blue-500/20 rounded text-sm text-blue-200">
                                <strong>AI Insight:</strong> {report.summary.insight}
                            </div>
                        </CardContent>
                    </Card>

                    {/* 2. Compliance & SOP */}
                    <Card className="bg-black/40 border-white/10">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2 text-purple-400">
                                <Shield size={20} /> Compliance Insights
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-3 text-sm">
                            <div className="flex justify-between border-b border-white/10 pb-2">
                                <span className="text-gray-400">Most Referenced SOP</span>
                                <span className="text-white font-medium">{report.compliance.topSOP}</span>
                            </div>
                            <div className="flex justify-between border-b border-white/10 pb-2">
                                <span className="text-gray-400">Missing Document</span>
                                <span className="text-red-400 font-medium">{report.compliance.missingDoc}</span>
                            </div>
                            <div className="bg-purple-500/10 p-3 rounded text-purple-200 text-xs">
                                💡 {report.compliance.recommendation}
                            </div>
                        </CardContent>
                    </Card>

                    {/* 3. Query Analytics */}
                    <Card className="bg-black/40 border-white/10">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2 text-cyan-400">
                                <Users size={20} /> Helpdesk Analytics
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-3">
                            <div>
                                <p className="text-xs text-gray-500 mb-2">Top Questions</p>
                                {report.queries.topQuestions.map((q: string, i: number) => (
                                    <div key={i} className="flex items-center gap-2 text-sm text-gray-300 mb-1">
                                        <div className="w-1.5 h-1.5 rounded-full bg-cyan-500"></div>
                                        {q}
                                    </div>
                                ))}
                            </div>
                            <div className="flex gap-4 mt-4">
                                <div>
                                    <p className="text-xs text-gray-500">Time Saved</p>
                                    <p className="text-lg font-bold text-white">{report.queries.timeSaved}</p>
                                </div>
                                <div>
                                    <p className="text-xs text-gray-500">Languages</p>
                                    <p className="text-lg font-bold text-white">{report.queries.languages}</p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* 4. Risk Intelligence */}
                    <Card className="bg-black/40 border-white/10">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2 text-red-400">
                                <AlertTriangle size={20} /> Risk Intelligence
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div>
                                <p className="text-xs text-gray-500 mb-2">High Delay Zones</p>
                                {report.risks.highDelayZones.map((z: any, i: number) => (
                                    <div key={i} className="flex justify-between text-sm mb-1">
                                        <span className="text-gray-300">{z.zone}</span>
                                        <span className="text-red-500 font-bold">{z.risk}</span>
                                    </div>
                                ))}
                            </div>
                            <div className="bg-red-500/10 p-3 rounded text-red-200 text-xs border border-red-500/20">
                                ⚠ {report.risks.alert}
                            </div>
                        </CardContent>
                    </Card>

                    {/* 5. AI Recommendations */}
                    <Card className="bg-gradient-to-br from-blue-900/20 to-purple-900/20 border-blue-500/30 col-span-1 md:col-span-2">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2 text-white">
                                <Zap size={20} className="text-yellow-400" /> Strategic Recommendations
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="grid md:grid-cols-2 gap-4">
                                {report.recommendations.map((rec: string, i: number) => (
                                    <div key={i} className="flex gap-3 p-3 bg-black/40 rounded-lg border border-white/5">
                                        <CheckCircle2 className="text-green-500 shrink-0" size={20} />
                                        <p className="text-sm text-gray-200">{rec}</p>
                                    </div>
                                ))}
                            </div>
                        </CardContent>
                    </Card>
                </div>
            )}
        </div>
    );
}
